language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  # Code checks
  - ./data_load.py --count 2 --stop-on-success
  - ./data_parse.py

  # Run codestyle checks
  - cd "$TRAVIS_BUILD_DIR"
  - pip install pycodestyle
  - pycodestyle --config=setup.cfg --statistics -v .
